name: Akraya Job Scraper

on:
  # Schedule to run every day at 15:00 UTC (8 AM PDT / 7 AM PST)
  schedule:
    - cron: '0 15 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scrape-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # THIS IS THE FIX: Install Google Chrome browser
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run the scraper script
        run: python scraper.py

      # This step uses a pre-built action to send an email with the results
      - name: Send email with job report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com # Use your email provider's SMTP server
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Daily Akraya Job Report"
          to: ${{ secrets.MAIL_TO }}
          from: GitHub Actions Scraper <${{ secrets.MAIL_USERNAME }}>
          body: "Akraya job listings for today. See attached report."
          attachments: 'akraya_jobs.html'
