name: Akraya Job Scraper

on:
  schedule:
    # Runs once every day at 15:00 UTC (8 AM PDT)
    - cron: '0 15 * * *'
  workflow_dispatch: # Allows you to run it manually from the Actions tab in GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      # --- THIS IS THE NEW, MORE RELIABLE METHOD ---
      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run scraper script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO:   ${{ secrets.EMAIL_TO }}
        run: python scraper.py
