name: Akraya Job Scraper

on:
  schedule:
    # Runs every day at 16:00, 18:00, 20:00, and 22:00 UTC
    # (Corresponds to 9am, 11am, 1pm, 3pm PDT)
    - cron: '0 16,18,20,22 * * *'
  workflow_dispatch: # Allows you to run it manually from the Actions tab in GitHub

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Run scraper script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO:   ${{ secrets.EMAIL_TO }}
        run: python scraper.py
